version: "3.7"

services:
  traefik:
    build: .
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true    
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik.yml:/etc/traefik.yml
